# Generated by Django 4.2.4 on 2023-11-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainRadar1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='programa_academicos',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=2000)),
                ('id_unico1', models.IntegerField(primary_key=True, serialize=False)),
                ('id_universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRadar1.universidad')),
            ],
        ),
    ]
