# Generated by Django 4.2.4 on 2023-11-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainRadar1', '0002_programa_academicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=2000)),
                ('precio', models.FloatField()),
                ('id_unico2', models.IntegerField(primary_key=True, serialize=False)),
                ('id_universidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRadar1.universidad')),
            ],
        ),
    ]
