# Generated by Django 4.2.4 on 2023-11-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainRadar1', '0003_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='curso_programa',
            fields=[
                ('id_unico4', models.IntegerField(primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRadar1.curso')),
                ('id_programa_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainRadar1.programa_academicos')),
            ],
        ),
    ]
