# Generated by Django 4.2.4 on 2023-11-01 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainRadar1', '0004_curso_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('descripcion', models.CharField(max_length=2000)),
                ('id_unico3', models.IntegerField(primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRadar1.curso')),
                ('id_programa_academico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRadar1.programa_academicos')),
                ('id_universidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRadar1.universidad')),
            ],
        ),
    ]
