# Generated by Django 4.2.4 on 2023-11-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainRadar1', '0005_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainRadar1.usuario'),
        ),
    ]
